# Generated 2022-01-19 from:
# /scratch/elec/t405-puhe/p/porjazd1/Metadata_Classification/TCN/asr_topic_speechbrain/mgb_asr/hyperparams.yaml
# yamllint disable
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [1234]

skip_training: True

output_folder: output_folder_layer_18_split_30_10_train_dev
output_folder_pretrained: pretrained/output_folder_layer_18_split_30_10_train_dev
label_encoder_file_request: !ref <output_folder>/label_encoder_request.txt

train_log: !ref <output_folder>/train_log.txt
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save

wav2vec2_hub: facebook/wav2vec2-large-xlsr-53
wav2vec2_folder: !ref <save_folder>/wav2vec2_checkpoint

# Training params
n_epochs: 5
audio_length: "None"
split_size: 30
step_size: 10

# batch size of 6 for 15 seconds, 4 for 20 seconds
dataloader_options:
    batch_size: 32
    shuffle: false

test_dataloader_options:
    batch_size: 1
    shuffle: false

lr: 0.001
lr_wav2vec2: 0.001

#freeze all wav2vec2
freeze_wav2vec2: True
#set to true to freeze the CONV part of the wav2vec2 model
freeze_wav2vec2_conv: True

label_encoder_request: !new:speechbrain.dataio.encoder.CategoricalEncoder

encoder_dims: 1024
n_classes: 9

bayesian_layer: !new:torchbnn.BayesLinear
    prior_mu: -0.0003087313089054078
    prior_sigma: 0.018001841381192207
    in_features: !ref <encoder_dims>
    out_features: !ref <n_classes>

# Wav2vec2 encoder
wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec2>
    freeze_feature_extractor: !ref <freeze_wav2vec2_conv>
    save_path: !ref <wav2vec2_folder>
    output_all_hiddens: True

avg_pool: !new:speechbrain.nnet.pooling.StatisticsPooling
    return_std: False

out_request: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <encoder_dims>
    n_neurons: !ref <n_classes>
    bias: False

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec2_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec2>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <n_epochs>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

kl_cost: !name:torchbnn.functional.bayesian_kl_loss
    model: !ref <bayesian_model>
    reduction: "mean"
    last_layer_only: False

# Functions that compute the statistics to track during the validation step.
accuracy_computer: !name:speechbrain.utils.Accuracy.AccuracyStats

f_score_error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

modules:
    wav2vec2: !ref <wav2vec2>
    bayesian_layer: !ref <bayesian_layer>

model: !new:torch.nn.ModuleList
      - [!ref <wav2vec2>, !ref <out_request>]

bayesian_model: !new:torch.nn.ModuleList
      - [!ref <bayesian_layer>]

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        bayesian_model: !ref <bayesian_model>
        counter: !ref <epoch_counter>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <output_folder_pretrained>/save/CKPT+2023-06-30+19-14-02+00
    loadables:
        model: !ref <model>
    paths:
        model: !ref <output_folder_pretrained>/save/CKPT+2023-06-30+19-14-02+00
